# Generated by Django 2.0.1 on 2020-08-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200827_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeentity',
            name='creat_time',
        ),
        migrations.AddField(
            model_name='storeentity',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='c198fe66b47a49af9c9a42ea59c59eba', primary_key=True, serialize=False, verbose_name='店号'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='last_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后变更时间'),
        ),
    ]
