# Generated by Django 2.0.1 on 2020-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200828_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeentity',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='storeentity',
            name='logo_width',
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store', verbose_name='LOGO'),
        ),
    ]
